site_name: g-2 modified DAQ Manual
theme:
  name: readthedocs

nav:
  - Home: index.md
  - Hardware Overview: hardware_overview.md
  - Software Dependencies: software_dependencies.md
  - Install and Build the Midas Frontends: installing_and_building.md
  - ODB Configurations: odb_config.md
  - Additional Software Add-ons: software_add_ons.md
  - Networking Tutorial: networking.md
  - Miscellaneous: miscellaneous_info.md

plugins:
  - search
  - pdf-export

markdown_extensions:
  - attr_list
