site_name: g-2 modified DAQ Manual
theme:
  name: readthedocs

nav:
  - Home: index.md
  - Hardware Overview: hardware_overview.md
  - Software Dependencies: software_dependencies.md
  - Install and Run the Midas Frontends: installing_and_building.md
  - ODB Configuration: odb_config.md
  - Midas Information: midas.md
  - Additional Software Add-ons: software_add_ons.md
  - Networking Tutorial: networking.md
  - Miscellaneous: miscellaneous_info.md

plugins:
  - search
  - pdf-export
  - git-revision-date-localized:
      enable_creation_date: false

markdown_extensions:
  - attr_list

extra_css:
- https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css
